version: '3.7'
services:
  mongodb_container:
    image: mongo:4.2.5
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

volumes:
  mongodb: